routes/web.php
<?php
Route::group(['middleware' => ['log']], function () {

    // Load All Course Package
    Route::get('loads/course-package-front-end/all', 'CoursePackageFrontendController@loadAllCourses');
    // Load Searching Course Package
    Route::get('loads/course-package-front-end/{keyword}', 'CoursePackageFrontendController@loadSearchAllCourses');
    // Load All Category Package
    Route::get('loads/course-package-front-end/categories/all', 'CoursePackageFrontendController@loadAllCategories');

    Route::get('loads/course-package-front-end/categories/{id}/courses', 'CoursePackageFrontendController@loadCategoryCourses');
    // Load SubCategory by Category Package
    Route::get('loads/course-package-front-end/subcategories/{id}', 'CoursePackageFrontendController@loadSubCategory');
    // Load All Course Order By Price Package
    Route::get('loads/course-package-front-end/orderby/prices', 'CoursePackageFrontendController@loadAllCoursesByPrices');
    // Load All Course Order By Price Package
    Route::get('loads/course-package-front-end/orderby/popular', 'CoursePackageFrontendController@loadAllCoursesByPopular');

    // Load All Course
    Route::get('loads/social-learning-course-front-end/all', 'CourseFrontEndSocialLearning@loadAllCourses');
    // Load Searching Course
    Route::get('loads/social-learning-course-front-end/{keyword}', 'CourseFrontEndSocialLearning@loadSearchAllCourses');
    // Load All Category
    Route::get('loads/social-learning-course-front-end/categories/all', 'CourseFrontEndSocialLearning@loadAllCategories');

    Route::get('loads/social-learning-course-front-end/categories/{id}/courses', 'CourseFrontEndSocialLearning@loadCategoryCourses');
    // Load SubCategory by Category
    Route::get('loads/social-learning-course-front-end/subcategories/{id}', 'CourseFrontEndSocialLearning@loadSubCategory');
    // Load All Course Order By Price
    Route::get('loads/social-learning-course-front-end/orderby/prices', 'CourseFrontEndSocialLearning@loadAllCoursesByPrices');
    // Load All Course Order By Price
    Route::get('loads/social-learning-course-front-end/orderby/popular', 'CourseFrontEndSocialLearning@loadAllCoursesByPopular');

    // Load Carts Frontend Data
    Route::get('loads/frontend/carts', 'CourseFrontEndSocialLearning@loadAllCarts');
    Route::get('loads/frontend/package-carts', 'CourseFrontEndSocialLearning@loadAllPackageCarts');

    // Course Packages
    Route::resource('course-package-frontend', 'CoursePackageFrontendController');

    // Pages
    Route::get('/cpages/{url}', [
        'as' => 'password.request',
        'uses' => 'PageController@showPage'
    ]);

    Route::get('/user/verify/{token}', 'Auth\RegisterController@verifyUser');

    // Reset Password
    Route::get('/password/reset', [
        'as' => 'password.request',
        'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm'
    ]);

    Route::post('/password/email', [
        'as' => 'password.email',
        'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail'
    ]);

    Route::get('/password/reset/{token}', [
        'as' => 'password.reset',
        'uses' => 'Auth\ResetPasswordController@showResetForm'
    ]);

    Route::post('/password/reset', [
        'as' => 'reset',
        'uses' => 'Auth\ResetPasswordController@reset'
    ]);


    Route::get('phpinfo', function () {
        return phpinfo();
    });

    Route::get('payments', 'HomeController@payments');

    Route::get('noPermission', 'DashboardController@noPermission')->name('noPermission');

    // Route::post('register', 'Auth\RegisterController@register');

    Route::get('social-learning', 'HomeController@index');


    Route::post('register', [
        'as' => 'register',
        'uses' => 'LoginController@postRegister'
    ]);


    // Route::post('login', [
    //     'as' => 'login',
    //     'uses' => 'LoginController@postLogin'
    // ]);

    Route::group(['middleware' => ['authen']], function () {

        // Load Carts Frontend Data
        Route::get('loads/carts', 'MyCourseSocialLearningController@loadAllCarts');
        Route::get('loads/package-carts', 'MyCourseSocialLearningController@loadAllPackageCarts');

        // Remove Item Cart
        Route::delete('carts/{course_id}/remove', 'MyCourseSocialLearningController@removeCourseFromCart');
        Route::delete('package-carts/{course_id}/remove', 'MyCourseSocialLearningController@removePackageCourseFromCart');

        // Sync Carts Data
        Route::post('sync/carts', [
            'as' => 'social-learning-my-course.sync-carts-data',
            'uses' => 'MyCourseSocialLearningController@syncCartsData'
        ]);

        // Payments
        Route::post('payments/register', [
            'as' => 'payments.register',
            'uses' => 'PaymentSocialLearningController@createTransaction'
        ]);

        // DB Proccess URL
        Route::get('payments/confirm/{id}', [
            'as' => 'payments.order.confirm',
            'uses' => 'PaymentSocialLearningController@confirmPayment'
        ]);

        Route::get('notification', [
            'as' => 'notification.setting',
            'uses' => 'NotificationSettingController@index'
        ]);

        Route::get('notification/all', [
            'as' => 'notification.show.all',
            'uses' => 'NotificationSettingController@showAll'
        ]);

        Route::put('notification', [
            'as' => 'notification.setting.update',
            'uses' => 'NotificationSettingController@update'
        ]);

        // Profile
        Route::resource('social-learning-profile', 'ProfileSocialLearningController');
        
        // Posts
        Route::resource('social-learning-posts', 'PostSocialLearningController');

        Route::put('me/update-image/social', 'ProfileController@changeSocialImage');

        // Badge
        Route::post('badges/{id}/claim', [
            'as' => 'badges.claim',
            'uses' => 'BadgeSocialLearningController@claim'
        ]);

        // Question
        Route::post('social-learning-questions/{id}/likes', [
            'as' => 'questions.like',
            'uses' => 'QuestionSocialLearningController@like'
        ]);

        Route::post('social-learning-questions/{id}/dislikes', [
            'as' => 'questions.dislike',
            'uses' => 'QuestionSocialLearningController@dislike'
        ]);

        Route::post('social-learning-questions/{id}/comments', [
            'as' => 'questions.comments',
            'uses' => 'QuestionSocialLearningController@postComment'
        ]);

        Route::post('social-learning-questions/comments/{id}/likes', [
            'as' => 'questions.comments.like',
            'uses' => 'QuestionSocialLearningController@likeComment'
        ]);

        Route::post('social-learning-questions/comments/{id}/dislikes', [
            'as' => 'questions.comments.dislike',
            'uses' => 'QuestionSocialLearningController@dislikeComment'
        ]);

        // Question
        Route::post('questions/{id}/likes', [
            'as' => 'questions.like',
            'uses' => 'QuestionController@like'
        ]);

        Route::post('questions/{id}/dislikes', [
            'as' => 'questions.dislike',
            'uses' => 'QuestionController@dislike'
        ]);

        Route::post('questions/{id}/comments', [
            'as' => 'questions.comments',
            'uses' => 'QuestionController@postComment'
        ]);

        Route::post('questions/comments/{id}/likes', [
            'as' => 'questions.comments.like',
            'uses' => 'QuestionController@likeComment'
        ]);

        Route::post('questions/comments/{id}/dislikes', [
            'as' => 'questions.comments.dislike',
            'uses' => 'QuestionController@dislikeComment'
        ]);


        /* Post */
        Route::post('/posts/{id}/likes', [
            'as' => 'like',
            'uses' => 'PostSocialLearningController@like'
        ]);

        Route::post('/posts/{id}/dislikes', [
            'as' => 'dislike',
            'uses' => 'PostSocialLearningController@dislike'
        ]);

        Route::post('/posts/{id}/comments', [
            'as' => 'comments',
            'uses' => 'PostSocialLearningController@postComment'
        ]);

        Route::post('/comments/{id}/likes', [
            'as' => 'comments.like',
            'uses' => 'PostSocialLearningController@likeComment'
        ]);

        Route::post('/comments/{id}/dislikes', [
            'as' => 'comments.dislike',
            'uses' => 'PostSocialLearningController@dislikeComment'
        ]);

        /* End Post */

        /* MasterPiece */
        Route::post('/posts-masterpieces/{id}/likes', [
            'as' => 'like.masterpieces',
            'uses' => 'MasterpieceSocialLearningController@like'
        ]);

        Route::post('/posts-masterpieces/{id}/dislikes', [
            'as' => 'dislike.masterpieces',
            'uses' => 'MasterpieceSocialLearningController@dislike'
        ]);

        Route::post('/posts-masterpieces/{id}/comments', [
            'as' => 'comments.masterpieces',
            'uses' => 'MasterpieceSocialLearningController@postComment'
        ]);

        Route::post('/comments-masterpieces/{id}/likes', [
            'as' => 'comments.like.masterpieces',
            'uses' => 'MasterpieceSocialLearningController@likeComment'
        ]);

        Route::post('/comments-masterpieces/{id}/dislikes', [
            'as' => 'comments.dislike.masterpieces',
            'uses' => 'MasterpieceSocialLearningController@dislikeComment'
        ]);

        /* End MasterPiece */

        /* Course */
        Route::post('/courses/{id}/join', 'CourseController@join');

        Route::post('/courses/{id}/leave', 'CourseController@leave');



        // Courses Pages

        Route::get('courses/{id}/sections-page', [
            'as' => 'courses.page.sections',
            'uses' => 'CourseController@sectionsPage'
        ]);

resources/views/social-learnings/course-package-front-end/essay/answer-child.blade.php
<div id="answer{{ $answer->id }}" class="col-lg-12">
    <div class=" m-t-20">
        <div class="card-box">
            <div class="media m-b-30">
                <a>
                    @if($answer->user->photo === null)
                        <img class="d-flex mr-3 rounded-circle thumb-sm"
                             src="/images/default.png" alt="Generic placeholder image">
                    @else
                        <img class="d-flex mr-3 rounded-circle thumb-sm"
                             src="/images/photo/{{ $answer->user->photo }}" alt="Generic placeholder image">
                    @endif
                </a>

                <div class="media-body">

                    <a href="{{ route('social-learning-posts.show', [$_SERVER['HTTP_HOST'], $answer->user->username]) }}">
                        <h4 class="text-primary font-16 m-0">
                            {{ $answer->user->fullname }}
                            <small class="text-muted">
                                <i class="ion-clock"></i>
                                {{ $answer->created_at->diffForHumans() }}
                            </small>
                        </h4>
                    </a>

                </div>

            </div>

            <p>{{ $answer->body }}</p>

            <hr>

            <div class="row">
                <div class="col-md-12">
                    <a class="post-icon" onclick="onAnswerLike({{ $answer->id }})">
                        <i class="fa fa-thumbs-o-up {{ $answer->likes()->where('user_id', Auth::id())->count() ? 'like' : '' }}">
                            {{ $answer->likes()->count() }}
                        </i>
                    </a>

                    <a class="post-icon" onclick="onAnswerDislike({{ $answer->id }})">
                        <i class="fa fa-thumbs-o-down {{ $answer->dislikes()->where('user_id', Auth::id())->count() ? 'dislike' : '' }}">
                            {{ $answer->dislikes()->count() }}
                        </i>
                    </a>

                    <a class="pull-right post-icon">
                        <p class="fa fa-comments-o"> {{ $answer->comments()->count() }} </p>
                    </a>
                </div>

            </div>
            <hr>

            <div>

                @foreach($answer->comments as $comment)
                    <div class="comment" style="background-colot:p ">
                        @if( Auth::user()->photo === null)
                            <img src="/images/default.png" alt="" class="comment-avatar">
                        @else
                            <img src="/images/photo/{{ Auth::user()->photo }}" alt="" class="comment-avatar">
                        @endif

                        <div class="comment-body">
                            <div class="comment-text">
                                <div class="comment-header">
                                    <a href="#" title="">{{ $comment->user->fullname }}</a>
                                    <span>about {{ $comment->created_at->diffForHumans() }}</span>
                                    <span class="float-right label label-primary text-white">
                                        <small>Pilih Best Answer</small>
                                    </span>
                                </div>
                                {{ $comment->body }}
                            </div>

                        </div>
                    </div>
                @endforeach

                <div class="media m-b-30">

                    @if(Auth::user()->photo === null)
                        <img class="d-flex mr-3 rounded-circle thumb-sm"
                             src="/images/default.png" alt="Generic placeholder image">
                    @else
                        <img class="d-flex mr-3 rounded-circle thumb-sm"
                             src="/images/photo/{{ Auth::user()->photo }}" alt="Generic placeholder image">
                    @endif

                    <div class="media-body">
                        <form id="formaddcomment" onsubmit="onAnswerComment({{ $answer->id }}); return false;"
                              method="post" data-parsley-validate>

                            <input id="answerBody{{ $answer->id }}" type="text" name="body"
                                   class="form-control"
                                   placeholder="Tulis komentar...">

                        </form>

                    </div>
                </div>
                <hr>
            </div>
        </div>

    </div>
</div>